AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: photo album
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LFX
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./LambdaCode
      Description: 'Lambda function for photo album'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::351062784755:role/service-role/codebuild-lambdaBuildProject-service-role'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1